---
version: 2
models:
- name: "Stocks_analysis1__ma_final"
  tags:
  - "prophecy_temp"
- name: "Stocks_analysis1__q1_final_sorted"
  tags:
  - "prophecy_temp"
- name: "Stocks_analysis1__q2_final"
  tags:
  - "prophecy_temp"
- name: "Stocks_analysis1__q3_final"
  tags:
  - "prophecy_temp"
